### ISSUE TITLE
Deserialize Function Runtime Error

### ISSUE THREAD

**Issue by ozgunay** [yucelalbar/RapidJSONSerDe#3]
Hi Yucel,

Thank you for this wonderful library. But these is a run-time error in `Entity::Deserialize(float* p, const rapidjson::Value & document, const std::string& k)` function. Because the function tries to write an integer value on a float pointer. 

And also Deserialize funtion unsignet int override seems to write signed integer for examle : `Entity::Deserialize(uint32_t* p, const rapidjson::Value & document, const std::string& k)`

Thank you.

**Comment by yucelalbar** [comment]
Hey @ozgunay! Thanks for using the lib and your feedback! Here is the latest commit regarding to fix: https://github.com/yucelalbar/RapidJSONSerDe/commit/de20b2323845bcc8a197853da5679b74258d2654
